#!/bin/bash
#SBATCH -J dohyung_project 
#SBATCH -o dohyung_project.o%j
#SBATCH -e dohyung_project.o%j
#SBATCH -p serial
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -t 06:00:00
#SBATCH --mail-user=dhpark@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

./a.out $WORK/collrank_data/ml10m_c10_test_rating_lsvm.dat $WORK/collrank_data/ml10m_c10_train_comps.dat $WORK/collrank_data/ml10m_c10_test_comps.dat 1

./a.out $WORK/collrank_data/ml10m/ml10m_c50_test_rating_lsvm.dat $WORK/collrank_data/ml10m/ml10m_c50_train_comps.dat $WORK/collrank_data/ml10m/ml10m_c50_test_comps.dat 1
 

